/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 动态详情
type FinderObject struct {
	ExportId                 *string                       `json:"export_id,omitempty"`
	CreateTime               *int64                        `json:"create_time,omitempty"`
	DeleteFlag               *int64                        `json:"delete_flag,omitempty"`
	Description              *string                       `json:"description,omitempty"`
	Medias                   *[]WechatChannelsMedia        `json:"medias,omitempty"`
	FinderUsername           *string                       `json:"finder_username,omitempty"`
	WechatChannelsAccountId  *string                       `json:"wechat_channels_account_id,omitempty"`
	CreatedSource            CreatedSourceType             `json:"created_source,omitempty"`
	WechatChannelsComponents *[]WxgWechatChannelsComponent `json:"wechat_channels_components,omitempty"`
	FeedsSourceType          FeedsSourceType               `json:"feeds_source_type,omitempty"`
	IsDisable                *bool                         `json:"is_disable,omitempty"`
	DisableMessage           *string                       `json:"disable_message,omitempty"`
	AuditStatus              AdStatus                      `json:"audit_status,omitempty"`
}
