/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MaterialAiAnnotationAddRequest struct {
	AccountId      *int64        `json:"account_id,omitempty"`
	OrganizationId *int64        `json:"organization_id,omitempty"`
	AnnotationList *[]Annotation `json:"annotation_list,omitempty"`
	ResourceType   *string       `json:"resource_type,omitempty"`
}
