/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 标注结果
type Annotation struct {
	ResourceId *string  `json:"resource_id,omitempty"`
	AigcFlag   AigcFlag `json:"aigc_flag,omitempty"`
}
