/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 视频号动态组件
type WxgWechatChannelsComponent struct {
	ComponentType WechatChannelsComponentType `json:"component_type,omitempty"`
	Icon          *string                     `json:"icon,omitempty"`
	Wording       *string                     `json:"wording,omitempty"`
	ComponentUuid *string                     `json:"component_uuid,omitempty"`
}
