/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AigcStatus : 用户标注的AIGC状态
type AigcStatus string

// List of AigcStatus
const (
	AigcStatus_UNKNOWN  AigcStatus = "AIGC_STATUS_UNKNOWN"
	AigcStatus_USE_HM   AigcStatus = "AIGC_STATUS_USE_HM"
	AigcStatus_USE_AIGC AigcStatus = "AIGC_STATUS_USE_AIGC"
)
