/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// WxgamePlayablePageEndTimeType : 小游戏试玩页组件结束时间类型
type WxgamePlayablePageEndTimeType string

// List of WxgamePlayablePageEndTimeType
const (
	WxgamePlayablePageEndTimeType_TYPE_UNKNOWN  WxgamePlayablePageEndTimeType = "WXGAME_PLAYABLE_PAGE_END_TYPE_UNKNOWN"
	WxgamePlayablePageEndTimeType_TIME_30       WxgamePlayablePageEndTimeType = "WXGAME_PLAYABLE_PAGE_END_TIME_30"
	WxgamePlayablePageEndTimeType_TIME_COMPLETE WxgamePlayablePageEndTimeType = "WXGAME_PLAYABLE_PAGE_END_TIME_COMPLETE"
)
