/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SmartCouponMode : 小店智券的开关
type SmartCouponMode string

// List of SmartCouponMode
const (
	SmartCouponMode_UNKNOWN SmartCouponMode = "SWITCH_STATUS_UNKNOWN"
	SmartCouponMode_OFF     SmartCouponMode = "SWITCH_STATUS_OFF"
	SmartCouponMode_ON      SmartCouponMode = "SWITCH_STATUS_ON"
)
