/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MaterialAiAnnotationAddResponseData struct {
	SuccessList *[]AnnotationSuccessResult `json:"success_list,omitempty"`
	FailList    *[]AnnotationFailResult    `json:"fail_list,omitempty"`
}
