/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// FeedsSourceType : 视频号动态类型
type FeedsSourceType string

// List of FeedsSourceType
const (
	FeedsSourceType_FREETRADE FeedsSourceType = "FEEDS_SOURCE_TYPE_FREETRADE"
	FeedsSourceType_NATIVE    FeedsSourceType = "FEEDS_SOURCE_TYPE_NATIVE"
)
