/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// CreatedSourceType : 视频号创建来源
type CreatedSourceType string

// List of CreatedSourceType
const (
	CreatedSourceType_UNKNOWN      CreatedSourceType = "CREATE_SOURCE_TYPE_UNKNOWN"
	CreatedSourceType_REWARD_QUEST CreatedSourceType = "CREATE_SOURCE_TYPE_REWARD_QUEST"
	CreatedSourceType_FREETRADE    CreatedSourceType = "CREATE_SOURCE_TYPE_FREETRADE"
)
