/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AigcSource : AIGC来源
type AigcSource string

// List of AigcSource
const (
	AigcSource_UNKNOWN AigcSource = "AIGC_SOURCE_UNKNOWN"
	AigcSource_MUSE    AigcSource = "AIGC_SOURCE_MUSE"
)
