/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AigcFlag : AIGC标识
type AigcFlag string

// List of AigcFlag
const (
	AigcFlag_UNKNOWN       AigcFlag = "AIGC_FLAG_UNKNOWN"
	AigcFlag_NOT_AI        AigcFlag = "AIGC_FLAG_NOT_AI"
	AigcFlag_USE_MUSE_AI   AigcFlag = "AIGC_FLAG_USE_MUSE_AI"
	AigcFlag_USE_OTHERS_AI AigcFlag = "AIGC_FLAG_USE_OTHERS_AI"
)
