/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/zhucenichenghao/marketing-api-go-sdk/pkg/ads/v3"
	"github.com/zhucenichenghao/marketing-api-go-sdk/pkg/api/v3"
	"github.com/zhucenichenghao/marketing-api-go-sdk/pkg/config/v3"
	"github.com/zhucenichenghao/marketing-api-go-sdk/pkg/errors"
	"github.com/zhucenichenghao/marketing-api-go-sdk/pkg/model/v3"
)

type OauthRefreshTokenExample struct {
	TAds                  *ads.SDKClient
	AccessToken           string
	ClientId              int64
	ClientSecret          string
	RefreshToken          string
	OauthRefreshTokenOpts *api.OauthRefreshTokenOpts
}

func (e *OauthRefreshTokenExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.ClientId = 789
	e.ClientSecret = "clientSecret_example"
	e.RefreshToken = "refreshToken_example"
	e.OauthRefreshTokenOpts = &api.OauthRefreshTokenOpts{}
}

func (e *OauthRefreshTokenExample) RunExample() (model.OauthRefreshTokenResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.Oauth().RefreshToken(ctx, e.ClientId, e.ClientSecret, e.RefreshToken, e.OauthRefreshTokenOpts)
}

func main() {
	e := &OauthRefreshTokenExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
